env:
  global:
  - VERSION=0.4.1
  - SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
  - RELEASE_VERSION=$VERSION+build.$TRAVIS_BUILD_NUMBER.sha.$SHORT_COMMIT_SHA
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /^[0-9]*\.[0-9]*\.[0-9]\+build.[0-9]*$/
before_install:
- mvn versions:set -DnewVersion=$RELEASE_VERSION
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
script:
- mvn package -DfinalName=gocd-websocket-notifier-$RELEASE_VERSION -DfinalVersion=$RELEASE_VERSION
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$VERSION+build.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GIT_TAG_USER:$GIT_TAG_AUTH_TOKEN@github.com/matt-richardson/gocd-websocket-notifier.git --tags
- ls -alR
deploy:
  provider: releases
  api_key:
    secure: i7IfoSUXSGm2ki04BL01EuEcPNEWpyZna4XeXQj07quzSoCqMOrb99YCKvXZ2PlyHubrMaMQKcPz43jOPnVfXOsrV5aaaKC0HgF5M/6i1NOvrAUzMZ69EfTspI1yOlc4oaZTJE1gScvVxNh0JDcml8rBqDJnM4U2cPXchn0z3Y8=
  file: target/gocd-websocket-notifier-$RELEASE_VERSION.jar
  skip_cleanup: true
  on:
    branch: master
    tags: false
    repo: matt-richardson/gocd-websocket-notifier
